### ISSUE TITLE
Intensity display in RViz

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/psen_scan_v2#111]
### Commit
2ff584f

### Steps to reproduce
How can the issue/bug be reproduced?
1. `roslaunch psen_scan_v2 psen_scan_v2.launch`

### Expected behavior
RViz should open with intensities displayed using a feasible colour mapping.

### Observed behavior
Scan messages are displayed all in red.

**Comment by martiniil** [comment]
Fixed here 86c9804
