### ISSUE TITLE
Rename DefaultScanRange

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/psen_scan_v2#130]
A DefaultScanRange is a ScanRange inside [0, 275] (degree).

This isn't obvious. So I'd suggest to rename `DefaultScanRange` to `ScanRange` and the unchecked(?) version `ScanRange` to something internal / private `TenthOfDegreeRange`.

_Originally posted by @martiniil in https://github.com/PilzDE/psen_scan_v2/pull/107#r542353865_

**Comment by cdoehn** [comment]
Should be resolved by PR #157

**Comment by jschleicher** [comment]
You can use `Fixes: #xx` in the Commit message to automatically link the corresponding issue.
