### ISSUE TITLE
Include include-what-you-use ( iwyu ) in CI

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/psen_scan_v2#143]
Related to #140 we should include this tool in our CI to keep the headers clean.

This should require adding iwyu in `ADDITIONAL_DEBS` of industrial_ci + adding the check to the CMake.
We could discuss if the default when running it locally should do it as well of if we depend it on some flag.

**Comment by jschleicher** [comment]
Would be great - but I'm not sure, if that is feasible at the moment. There are lots of false posivitves suggesting to include the private boost headers 
```diff
- #include <boost/optional.hpp>  // lines 24-24
+ #include <boost/optional/optional.hpp>                      // for optional
```
see for example https://github.com/include-what-you-use/include-what-you-use/issues/806 suggesting [Include Mappings](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md#include-mappings).
