### ISSUE TITLE
No data will be sent, when setting angle_end to 1.57

### ISSUE THREAD

**Issue by cdoehn** [PilzDE/psen_scan_v2#181]
### Commit
[f99827](https://github.com/PilzDE/psen_scan_v2/commit/f99827ac3a7a8d377bb4ca52b23a1e6eaa042c97)

### Steps to reproduce

roslaunch psen_scan_v2 psen_scan_v2.launch sensor_ip:=192.168.0.100 angle_end:=1.57

### Expected behavior

The scanner should send data, which is shown in rviz. But no data above 1.57 radians.

### Observed behavior

First time:
[ERROR] [1618158199.095220143]: The monitoring frame ranges do not cover the whole scan range

Second time:
Same behaviour but no error message is shown.

**Comment by martiniil** [comment]
In the function `toLaserScan()` we have to take account for individual monitoring frames being empty, while the whole scan still contains data.

**Comment by cdoehn** [comment]
Should be solved by https://github.com/PilzDE/psen_scan_v2/pull/183
