### ISSUE TITLE
Exception from the node not caught

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/psen_scan_v2#271]
The exception  “Unknown operation result code” raised by the driver are not catched by the ROS wrapper and causing the node to terminate immediately. 

https://github.com/PilzDE/psen_scan_v2/blob/d3b2405e3edf134e76123471a84b4ede8e3050e6/src/psen_scan_driver.cpp#L118 `std::future.wait()` doesn't retrieve the result and thus lets the exception unhandled. To properly make use of the try...catch contruction, there should be a call that handles the result of the thread.

While the return code should still be negative in case of failures, it is desirable, to get the ROS_ERROR from https://github.com/PilzDE/psen_scan_v2/blob/d3b2405e3edf134e76123471a84b4ede8e3050e6/src/psen_scan_driver.cpp#L120-L122 instead of just terminating.

![psen-scan-throw](https://user-images.githubusercontent.com/29709205/139871946-fa4cb15f-5cbc-4bfd-91d5-e404f2714f1e.jpg)

**Comment by martiniil** [comment]
Possible solution:

- Give UDP client access to `scanner_has_started` promise and catch exception of `message_callback`
- Do not throw in callback but let state machine set exception in `scanner_has_started` promise

**Comment by martiniil** [comment]
With #272 the output is now as follows (the hex code will be different)
![Screenshot (17)](https://user-images.githubusercontent.com/35950815/140500580-00dfa2db-0105-4a31-a28d-09b34a0365c0.png)
