### ISSUE TITLE
Could not find a package configuration file provided by "fmt"

### ISSUE THREAD

**Issue by AmmarAlbakri** [PilzDE/psen_scan_v2#323]
### Steps to reproduce
How can the issue/bug be reproduced?
1. git clone https://github.com/PilzDE/psen_scan_v2.git
2 . cd ~/catkin_ws
3. catkin_make

### Expected behavior
catkin make success

### Observed behavior
CMake Error at psen_scan_v2/CMakeLists.txt:47 
By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

### Possible Solution
sudo apt install libfmt-dev
this is the required package which must be mentioned as a dependency for this repository

**Comment by martiniil** [comment]
Build-dependencies of a ROS package are usually mentioned in `package.xml` and you can install them using [rosdep](http://wiki.ros.org/rosdep).

This is standard procedure for ROS developers. However, if you just want to use our package, I do not recommend building it from source.
