### ISSUE TITLE
ROS 2 humble issue

### ISSUE THREAD

**Issue by padhupradheep** [PilzDE/psen_scan_v2#340]
Hey I somehow got the Pilz package running on ROS 2 humble. however, I've these issues below:

```
Timeout while waiting for the scanner to start! Retrying... (Please check the ethernet connection or contact PILZ support if the error persists.)


[psen_scan_v2_node-1] [WARN] [1709230068.517020214] [StateMachine]: No transition in state "WaitForStartReply" for event "ReplyReceiveError".
```

any suggestion on where to dig?

I'm able to ping the scanners for your information

**Comment by padhupradheep** [comment]
Okay, got passed it. Now scanner fails any idea?

[psen_scan_v2_node-1] [INFO] [1709234749.385084232] [Scanner]: Start scanner called.
[psen_scan_v2_node-1] [INFO] [1709234749.402576267] [ScannerController]: Scanner start failed.

**Comment by PilzES** [comment]
Hi, sorry for the late reply.

This error usually occurs when you start the ROS2 driver with the Master or Master+Subscribers scanner with an incorrect configuration. In the launch files you will find the following option that you have to put how many subscribers you have in your configuration:

  
  <arg name="nr_subscribers" default="0" />

If you have started the ROS2 driver with the wrong configuration it is necessary to restart the scanners and restart the ROS2 driver with the correct configuration of your setup.

If this is not your case, please let me know.

**Comment by padhupradheep** [comment]
Ah forgot to update it here.. we got that too fixed.. 

We made our own work around version for Humble: https://github.com/neobotix/psen_scan_v2/commit/c60a691d92023a23cc01c6ca1b842aea68576710

Just in case if it could help someone in the near future. 

Thanks for the time.

**Comment by PilzES** [comment]
Yes I see, thanks for sharing.
I also want you to send the link to the repository and official branch(Humble) where we are working for the PSENscan ROS2 driver. It is still under development and not finished, but it is the most advanced one.
- https://github.com/PilzES/psen_scan_v2-2/tree/humble
