### ISSUE TITLE
Maximum Range of the Scanner

### ISSUE THREAD

**Issue by tann1504** [PilzDE/psen_scan_v2#70]
Hello,
We are planning to use your laser scanner, and i have been digging the source code to better understand the scanner parameters. I see that max. range is hardcoded as 10m. Is this the maximum value that we can use or is it adjustable considering maximum scanner range is listed as 40m?

**Comment by jschleicher** [comment]
Yep, according to the datasheet the max_range is 40 meters. Thank you very much for your report - we'll fix the code to be consistent with the datasheet.
